### ISSUE TITLE
linux上编译不通过

### ISSUE THREAD

**Issue by fouber** [fex-team/fis-parser-sass#23]
报错信息：

```bash
Downloading http://fisstatic.duapp.com/addons/fis-sass/3.1.0/linux-x64/0.9.11/binding.node ...
Received 512K...
Received 1026K...
Received 1543K...
Received 1753K total.
Test failed!
make: Entering directory `/home/zhangyl/soft/lib/node_modules/fis-parser-sass/node_modules/fis-sass/build'
  CXX(target) Release/obj.target/binding/src/binding.o
cc1plus: error: unrecognized command line option "-std=c++0x"
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/home/zhangyl/soft/lib/node_modules/fis-parser-sass/node_modules/fis-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/zhangyl/soft/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 2.6.18-164.el5
gyp ERR! command "node" "/home/zhangyl/soft/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zhangyl/soft/lib/node_modules/fis-parser-sass/node_modules/fis-sass
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
Build failed
npm ERR! fis-sass@3.1.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fis-sass@3.1.3 install script.
npm ERR! This is most likely a problem with the fis-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fis-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.18-164.el5
npm ERR! command "/home/zhangyl/soft/node/bin/node" "/home/zhangyl/soft/bin/npm" "install" "-g" "fis-parser-sass"
npm ERR! cwd /home/zhangyl
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/zhangyl/npm-debug.log
npm ERR! not ok code 0
```

**Comment by fouber** [comment]
nodejs版本：``v0.10.26``

**Comment by 2betop** [comment]
额，目测是 gcc 版本太低了，小于 gcc v4.3。同时预编译的版本可能因为某些原因（比如  glibc 太低）不能通用。

**Comment by fouber** [comment]
@2betop 

看到了。。。

**Comment by nimojs** [comment]
@2btop @fouber 
请问最后是如何解决的，我的版本信息是
````
node v0.12.5
gcc 版本 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
```
