### ISSUE TITLE
fis-parser-sass插件安装失败 

### ISSUE THREAD

**Issue by qiaosang** [fex-team/fis-parser-sass#33]
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
node: v0.12.7
npm: 2.11.3
npm install -g fis-parser-sass
\
> fis-sass@3.1.3 install /apps/node-v0.12.7-linux-x64/lib/node_modules/fis-parser-sass/node_modules/fis-sass
> node build.js

Downloading http://fisstatic.duapp.com/addons/fis-sass/3.1.0/linux-x64/0.12.0/binding.node ...
Received 522K...
Received 1036K...
Received 1553K...
Received 1753K total.
Test failed!
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/apps/node-v0.12.7-linux-x64/lib/node_modules/fis-parser-sass/node_modules/fis-sass/build'
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cpp: In function ‘Sass_Import** sass_importer2(const char*, const char*, void*)’:
../src/binding.cpp:27: warning: null argument where non-null required (argument 1)
../src/binding.cpp:28: warning: null argument where non-null required (argument 1)
../src/binding.cpp: In function ‘void GetStats(v8::Handle<v8::Object>, Sass_Context*)’:
../src/binding.cpp:95: error: ‘nullptr’ was not declared in this scope
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/apps/node-v0.12.7-linux-x64/lib/node_modules/fis-parser-sass/node_modules/fis-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/apps/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-925.431.29.2.el6.x86_64
gyp ERR! command "node" "/apps/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /apps/node-v0.12.7-linux-x64/lib/node_modules/fis-parser-sass/node_modules/fis-sass
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
Build failed
npm ERR! Linux 2.6.32-925.431.29.2.el6.x86_64
npm ERR! argv "/apps/node-v0.12.7-linux-x64/bin/node" "/apps/node-v0.12.7-linux-x64/bin/npm" "install" "-g" "fis-parser-sass"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! fis-sass@3.1.3 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fis-sass@3.1.3 install script 'node build.js'.
npm ERR! This is most likely a problem with the fis-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fis-sass
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:

**Comment by qiaosang** [comment]
什么原因 这个插件老是安装不上，centos6.5

**Comment by 2betop** [comment]
用 `fis-parser-node-sass` 吧

**Comment by qiaosang** [comment]
前段的框架现在是用的fis-parser-sass  服务器上得装这个

**Comment by qiaosang** [comment]
安装jello & lights

    npm install lights -g
    npm install jello -g
    jello -v

快速上手

    通过 lights 下载 jello-demo，或者通过 git clone jello-demo.

     lights install jello-demo

    安装插件

    npm install -g fis-parser-marked
    npm install -g fis-parser-utc
    npm install -g fis-parser-sass

    编译预览

     cd jello-demo
     jello release
     jello server start

jello用的这个

**Comment by 2betop** [comment]
`fis-parser-node-sass` 和 `fis-parser-sass` 使用方式是一样的，唯一不同的是一个是我们编译二进制包，一个是node-sass 编译二进制包。我们编译是为了编译机上能用。现在看来我们编译的二进制包在你的机器上不能，所以你可以尝试下 `fis-parser-node-sass`。如果一定要用 `fis-parser-sass`，只能本地编译了，得安装 `node-gyp`

**Comment by qiaosang** [comment]
node-gyp 安装了？    求怎么本地编译，源码里么有 binding.gyp

**Comment by 2betop** [comment]
额，还需要升级 gcc 4.6 最好是 4.8 .

**Comment by qiaosang** [comment]
jello release报  用  fis-parser-node-sass后
fis.config.set('modules.parser', {
    sass : 'sass',
    scss: 'sass'
});

fis.config.set('roadmap.ext', {
    sass: 'css',
    scss: 'css'
});


 报：
Can't find `compass/css3` in `modal`

**Comment by qiaosang** [comment]
升级gcc4.8.5 还是装不上 
fis-parser-sass 这插件能不能用？？网上这么多人说装不上
到底需要什么环境，什么版本要求
gcc，node，npm等等版本要求等

**Comment by xiangshouding** [comment]
@qiaosang 

第一，你装上了 gcc4.8 只是第一步，你得保证编译的时候，也就是 node-gyp 选中的编译器是 gcc4.8
第二，具体编译的时候，可能会报错，报错把报的错贴上来
第三，node-gyp 的使用方式，可以 Google 一下，比较简单。
第四，也时最重要的一点，我们提供了若干机器上能跑的二进制包，跑不了的只能自行补充相关知识，从源码编译起

**Comment by g8up** [comment]
我在安装这个时也遇到了问题
```
> fis-sass@3.1.3 install D:\Program Files (x86)\nodejs4.4\node_modules\fis3-parser-sass\node_modules\fis-sass
> node build.js

Downloading http://fisstatic.duapp.com/addons/fis-sass/3.1.0/win32-ia32/0.12.0/binding.node ...
Received 513K...
Received 832K total.
Test failed!
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

D:\Program Files (x86)\nodejs4.4\node_modules\fis3-parser-sass\node_modules\fis-sass>if not defined npm_config_node_gyp (node "D:\Program Files (x86)\
nodejs4.4\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Micros
oft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Program Files (x86)\nodejs4.4\no
de_modules\fis3-parser-sass\node_modules\fis-sass\build\binding.sln]
gyp ERR! build error
```
被坑了两天了，也是没谁了,说多了都是泪。。。
换`fis3-parser-node-sass` 正常~

https://github.com/fex-team/fis3 的`常用插件`里赶紧更新啊~

**Comment by chenweidong** [comment]
jello release 怎么由使用fis-parser-sass改为使用 fis-parser-node-sass
